# Delly build script

language: cpp

sudo: false

matrix:
  include:
    - env: MYCC="gcc-4.8" MYCXX="g++-4.8"
      os: linux
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    - env: MYCC="gcc-5" MYCXX="g++-5"
      os: linux
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env: MYCC="gcc-6" MYCXX="g++-6"
      os: linux
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

    - env: MYCC="clang" MYCXX="clang++"
      os: osx

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version

script:
  - make all
