# Delly build script

language: cpp

matrix:
  include:
    - env: MYCC="gcc-4.8" MYCXX="g++-4.8"
      os: linux
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    - env: MYCC="gcc-5" MYCXX="g++-5"
      os: linux
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env: MYCC="gcc-6" MYCXX="g++-6"
      os: linux
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

    - env: MYCC="gcc" MYCXX="g++"
      os: osx
      osx_image: xcode8.3

    - env: MYCC="gcc" MYCXX="g++"
      os: osx
      osx_image: xcode7.3


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq liblzma-dev libbz2-dev libboost-dev libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version

script:
  - make all
